language:
  - rust
  - node_js
cache: cargo
sudo: required
services: docker

node_js:
  - "node"

rust:
  - stable
  - beta
  - nightly

env:
  matrix:
    - TARGET="x86_64-unknown-linux-gnu"
    - TARGET="mips-unknown-linux-gnu"
    - TARGET="mipsel-unknown-linux-gnu"
    - TARGET="mips64-unknown-linux-gnuabi64"
    - TARGET="mips64el-unknown-linux-gnuabi64"
    - TARGET="aarch64-unknown-linux-gnu"

addons:
  apt:
    packages:
      - build-essential

before_install:
  - command -v cross 1>/dev/null || cargo install cross
  - npm install -g npm@latest
  - npm install -g ganache-cli@latest truffle@latest

script:
  - cross build --target $TARGET --verbose --all
  - cross test --target $TARGET --verbose --all

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - rust: stable
      ? env
      ? before_install
      script:
        - rustup component add rustfmt-preview
        - cargo fmt --all -- --check
    - rust: stable
      ? env
      ? before_install
      before_script:
      - source scripts/chain-prep.sh
      script:
      - cargo test --verbose -- --ignored testnet

