[package]
name = "guac_rs"
version = "0.1.0"
authors = ["Ben Wang <wangben3@gmail.com>"]

[dependencies]
env_logger = "0.5"
actix = "0.5.7"
actix-web = "0.6.7"
rand = "0.4.2"
futures = "0.1"
failure_derive = "*"
uuid = { version = "0.5", features = ["serde", "v4"] }
althea_types = { path = "../althea_rs/althea_types" }
num256 = { path = "../althea_rs/num256" }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
failure = "0.1.1"
base64 = "0.9.0"
tiny-keccak = "1.4.1"
mockito = "0.9.1"
web3 = "0.3.0"
lazy_static = "1.0"
ethcore-transaction = {git="https://github.com/paritytech/parity.git"}
ethkey = {git="https://github.com/paritytech/parity.git"}
rlp = {git="https://github.com/paritytech/parity.git", path="util/rlp"}
ethereum-types = "0.3.1"
ethabi-derive = "5.1.2"
ethabi = "5.1.1"
multihash = "0.7.0"
hex = "0.3.2"
diesel = { version = "1.0.0-beta1", features = ["sqlite"] }
dotenv = "0.10"
qutex = "^0.2"

[patch.crates-io]
ethereum-types = {git="https://github.com/kingoflolz/primitives.git"}
